FROM python:3.13 AS base

WORKDIR /app

RUN pip install uv

FROM base AS builder

WORKDIR /app

COPY independent_consumer/pyproject.toml independent_consumer/uv.lock ./
COPY independent_consumer .
RUN uv sync --frozen

FROM base AS runtime

WORKDIR /app

COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app .

RUN groupadd -g 1234 independent_consumer && \
    useradd -m -u 1234 -g independent_consumer independent_consumer

RUN chown -R independent_consumer:independent_consumer /app

USER independent_consumer

EXPOSE 8002

CMD ["/app/.venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]