"""create_inbox_messages

Revision ID: 1bdea85f0453
Revises: 
Create Date: 2026-09-17 23:48:25.093602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bdea85f0453'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_messages',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_on_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_on_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inbox_messages_unprocessed', 'inbox_messages', ['received_on_utc', 'processed_on_utc'], unique=False, postgresql_include=['id', 'type', 'content'], postgresql_where=sa.text('processed_on_utc IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inbox_messages_unprocessed', table_name='inbox_messages', postgresql_include=['id', 'type', 'content'], postgresql_where=sa.text('processed_on_utc IS NULL'))
    op.drop_table('inbox_messages')
    # ### end Alembic commands ###
